version: "3.8"
services:
  gpu-jupyter:
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8848:8888
    volumes:
      - ./data:/home/jovyan/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${UID}
      NB_GID: ${GID}
    # enable sudo permissions
    user:
      "root"
    restart: always
